=== kinny94/CSHL-practice/Mascot Parser Files/config/mascot_security_1_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
	@(#)$Source: /vol/cvsroot/parser/xml/schema/mascot_security_1_0.xsd,v $
	@(#)$Revision: 1.2 $
	@(#)$Name:  $
-->
<xsd:schema 
	xmlns:mss="http://www.matrixscience.com/xmlns/schema/mascot_security_1_0"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.matrixscience.com/xmlns/schema/mascot_security_1_0"
	elementFormDefault="qualified">

    <xsd:annotation>
        <xsd:documentation xml:lang="en-GB">
        Xml-schema used by msparser to validate all security-related xml-documents. 
        Client application should supply explicit location of this document in order to use msparser security API.
        </xsd:documentation>
    </xsd:annotation>

<!-- Version validation elements -->
    <xsd:simpleType name="majorVersion_t">
        <xsd:restriction base="xsd:unsignedShort">
            <xsd:enumeration value="1"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="minorVersion_t">
        <xsd:restriction base="xsd:unsignedShort">
            <xsd:maxInclusive value="1" />
        </xsd:restriction>
    </xsd:simpleType>
    
<!-- Top-level elements definitions -->
    <xsd:element name="security_options" type="mss:security_options_t" />
    <xsd:element name="security_tasks" type="mss:security_tasks_t" />
    <xsd:element name="security_groups" type="mss:security_groups_t" />
    <xsd:element name="security_users" type="mss:security_users_t" />
    <xsd:element name="security_session" type="mss:security_session_t" />
    
    <xsd:complexType name="security_options_t">
        <xsd:sequence>
            <xsd:element name="options" type="mss:options_t" />
        </xsd:sequence>
        <xsd:attribute name="majorVersion" type="mss:majorVersion_t" use="required" />
        <xsd:attribute name="minorVersion" type="mss:minorVersion_t" use="required" />
    </xsd:complexType>
    
    <xsd:complexType name="security_tasks_t">
        <xsd:sequence>
            <xsd:element name="tasks" type="mss:tasks_list_t" />
        </xsd:sequence>
        <xsd:attribute name="majorVersion" type="mss:majorVersion_t" use="required" />
        <xsd:attribute name="minorVersion" type="mss:minorVersion_t" use="required" />
    </xsd:complexType>
    
    <xsd:complexType name="security_groups_t">
        <xsd:sequence>
            <xsd:element name="last_groupID" type="xsd:integer" />
            <xsd:element name="all_groups" type="mss:groups_list_t" />
        </xsd:sequence>
        <xsd:attribute name="majorVersion" type="mss:majorVersion_t" use="required" />
        <xsd:attribute name="minorVersion" type="mss:minorVersion_t" use="required" />
    </xsd:complexType>
    
    <xsd:complexType name="security_users_t">
        <xsd:sequence>
            <xsd:element name="last_userID" type="xsd:integer" />
            <xsd:element name="all_users" type="mss:users_list_t" />
        </xsd:sequence>
        <xsd:attribute name="majorVersion" type="mss:majorVersion_t" use="required" />
        <xsd:attribute name="minorVersion" type="mss:minorVersion_t" use="required" />
    </xsd:complexType>
    
    <xsd:complexType name="security_session_t">
        <xsd:sequence>
            <xsd:element name="session_data" type="mss:session_data_t" />
        </xsd:sequence>
        <xsd:attribute name="majorVersion" type="mss:majorVersion_t" use="required" />
        <xsd:attribute name="minorVersion" type="mss:minorVersion_t" use="required" />
    </xsd:complexType>
    
<!-- Detailed types definitions -->

    <xsd:complexType name="options_t">
        <xsd:sequence>
            <xsd:element name="securityEnabled" type="xsd:string" />
            <xsd:element name="sessionTimeout" type="xsd:unsignedLong" />
            <xsd:element name="defaultPasswordExpiryTime" type="xsd:unsignedLong" />
            <xsd:element name="minimumPasswordLength" type="xsd:unsignedInt" />
            <xsd:element name="useSessionCookies" type="xsd:string" />
            <xsd:element name="verifySessionIPAddress" type="xsd:string" />
            <xsd:element name="integraAppServerURL" type="xsd:string" />
            <xsd:element name="integraDatabaseName" type="xsd:string" />
            <xsd:element name="integraOracleServerName" type="xsd:string" />
            <xsd:element name="logLevel" type="xsd:integer" />
            <xsd:element name="logFileName" type="xsd:string" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="task_t">
        <xsd:sequence>
            <xsd:element name="task_id" type="xsd:integer" />
            <xsd:element name="short_desc" type="xsd:string" />
            <xsd:element name="long_desc" type="xsd:string" />
            <xsd:element name="task_name" type="xsd:string" />
            <xsd:element name="type" type="xsd:integer" />
            <xsd:element name="values_array" type="mss:values_array_t" />
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="group_data_t">
        <xsd:sequence>
            <xsd:element name="group_id" type="xsd:integer" />
            <xsd:element name="group_name" type="xsd:string" />
            <xsd:element name="users" type="mss:users_id_list_t" />
            <xsd:element name="permitted_tasks" type="mss:tasks_list_t" />
            <xsd:element name="custom_parameters" type="mss:parameters_list_t" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="user_data_t">
        <xsd:sequence>
            <xsd:element name="userID" type="xsd:integer" />
            <xsd:element name="userName" type="xsd:string" />
            <xsd:element name="fullName" type="xsd:string" />
            <xsd:element name="encryptedPassword" type="xsd:string" />
            <xsd:element name="passwordExpiry" type="xsd:unsignedLong" />
            <xsd:element name="emailAddress" type="xsd:string" />
            <xsd:element name="accountEnabled" type="xsd:string" />
            <xsd:element name="userType" type="xsd:integer" />
            <xsd:element name="custom_parameters" type="mss:parameters_list_t" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="session_data_t">
        <xsd:sequence>
            <xsd:element name="emailAddress" type="xsd:string" minOccurs="0"/>
            <xsd:element name="fullUserName" type="xsd:string" minOccurs="0" />
            <xsd:element name="ipAddress" type="xsd:string" minOccurs="0" />
            <xsd:element name="lastAccessed" type="xsd:unsignedLong" />
            <xsd:element name="securityEnabled" type="xsd:string" minOccurs="0"/>
            <xsd:element name="timeout" type="xsd:unsignedLong" />
            <xsd:element name="userID" type="xsd:integer" minOccurs="0" />
            <xsd:element name="userName" type="xsd:string" minOccurs="0" />
            <xsd:element name="userType" type="xsd:integer" minOccurs="0" />
            <xsd:element name="verifyAddress" type="xsd:string" minOccurs="0" />
            <xsd:element name="custom_parameters" type="mss:parameters_list_t" />
            <xsd:element name="permitted_tasks" type="mss:tasks_list_t" />
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="param_t">
        <xsd:sequence>
            <xsd:element name="paramName" type="xsd:string" />
            <xsd:element name="paramValue" type="xsd:string" />
        </xsd:sequence>
    </xsd:complexType>
    
<!-- Lists and arrays. First, lists of simple data type elements. -->

    <xsd:complexType name="values_array_t">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="value" type="xsd:string" />
        </xsd:choice>
    </xsd:complexType>
    
    <xsd:complexType name="users_id_list_t">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="user_id" type="xsd:integer" />
        </xsd:choice>
    </xsd:complexType>
    
<!-- Now go the lists of complex objects -->

    <xsd:complexType name="tasks_list_t" >
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="task" type="mss:task_t" />
        </xsd:choice>
    </xsd:complexType>
    
    <xsd:complexType name="groups_list_t">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="group_data" type="mss:group_data_t" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="users_list_t">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="user_data" type="mss:user_data_t" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="parameters_list_t">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="param" type="mss:param_t" />
        </xsd:choice>
    </xsd:complexType>
   
</xsd:schema>

=== kinny94/CSHL-practice/Mascot Parser Files/config/security_tasks.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<mss:security_tasks xmlns:mss="http://www.matrixscience.com/xmlns/schema/mascot_security_1_0" majorVersion="1" minorVersion="0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.matrixscience.com/xmlns/schema/mascot_security_1_0 ../config/mascot_security_1_0.xsd">

  <mss:tasks>
    <mss:task>
      <mss:task_id>1</mss:task_id>
      <mss:short_desc>SEARCH: Allow pmf searches</mss:short_desc>
      <mss:long_desc>Unless this is set, the user will not be able to perform any peptide mass fingerprint searches.</mss:long_desc>
      <mss:task_name>SECTASK_ALLOWPMF</mss:task_name>
      <mss:type>0</mss:type>
      <mss:values_array>
        <mss:value>true</mss:value>
      </mss:values_array>
    </mss:task>
    <mss:task>
      <mss:task_id>2</mss:task_id>
      <mss:short_desc>SEARCH: Allow ms-ms (and SQ) searches</mss:short_desc>
      <mss:long_desc>Unless this is set, the user will not be able to perform any ms-ms or sequence tag searches.</mss:long_desc>
      <mss:task_name>SECTASK_ALLOWMSMS</mss:task_name>
      <mss:type>0</mss:type>
      <mss:values_array>
        <mss:value>true</mss:value>
      </mss:values_array>
    </mss:task>
    <mss:task>
      <mss:task_id>3</mss:task_id>
      <mss:short_desc>SEARCH: Allow msms no enzyme searches</mss:short_desc>
      <mss:long_desc>Unless this is set, the user will not be able to perform any no enzyme searches on ms-ms or sequence tag data.</mss:long_desc>
      <mss:task_name>SECTASK_ALLOWMSMSNOENZYME</mss:task_name>
      <mss:type>0</mss:type>
      <mss:values_array>
        <mss:value>true</mss:value>
      </mss:values_array>
    </mss:task>
    <mss:task>
      <mss:task_id>4</mss:task_id>
      <mss:short_desc>SEARCH: Allow no enzyme pmf searches</mss:short_desc>
      <mss:long_desc>Unless this is set, the user will not be able to perform any no enzyme searches on pmf data. It is not usually sensible to perform such searches.</mss:long_desc>
      <mss:task_name>SECTASK_ALLOWPMFNOENZYME</mss:task_name>
      <mss:type>0</mss:type>
      <mss:values_array>
        <mss:value>true</mss:value>
      </mss:values_array>
    </mss:task>
    <mss:task>
      <mss:task_id>5</mss:task_id>
      <mss:short_desc>SEARCH: Maximum number of concurrent searches per ip address</mss:short_desc>
      <mss:long_desc>This can be used to decrease (but not increase) the default setting in mascot.dat.</mss:long_desc>
      <mss:task_name>SECTASK_MAXCONCURRENTSEARCHES</mss:task_name>
      <mss:type>2</mss:type>
      <mss:values_array>
        <mss:value>0</mss:value>
      </mss:values_array>
    </mss:task>
    <mss:task>
      <mss:task_id>6</mss:task_id>
      <mss:short_desc>SEARCH: Maximum mascot search job priority</mss:short_desc>
      <mss:long_desc>Job priority can either be changed from the status screen, or from Mascot Daemon. Priority is in the range -10 to +10.</mss:long_desc>
      <mss:task_name>SECTASK_MAXJOBPRIORITY</mss:task_name>
      <mss:type>2</mss:type>
      <mss:values_array>
        <mss:value>0</mss:value>
      </mss:values_array>
    </mss:task>
    <mss:task>
      <mss:task_id>7</mss:task_id>
      <mss:short_desc>SEARCH: Maximum number of queries per search</mss:short_desc>
      <mss:long_desc>This overrides the default setting in mascot.dat - either above or below that value.</mss:long_desc>
      <mss:task_name>SECTASK_MAXQUERIES</mss:task_name>
      <mss:type>2</mss:type>
      <mss:values_array>
        <mss:value>0</mss:value>
      </mss:values_array>
    </mss:task>
    <mss:task>
      <mss:task_id>8</mss:task_id>
      <mss:short_desc>SEARCH: Maximum execution time</mss:short_desc>
      <mss:long_desc>This is the maximum elapsed time in seconds - it is not the maximum cpu time, and therefore will be affected by how busy the server is.</mss:long_desc>
      <mss:task_name>SECTASK_MAXEXECUTIONTIME</mss:task_name>
      <mss:type>2</mss:type>
      <mss:values_array>
        <mss:value>0</mss:value>
      </mss:values_array>
    </mss:task>
    <mss:task>
      <mss:task_id>9</mss:task_id>
      <mss:short_desc>SEARCH: Allow all fasta databases to be searched</mss:short_desc>
      <mss:long_desc>By default no databases may be searched.</mss:long_desc>
      <mss:task_name>SECTASK_ALLFASTA</mss:task_name>
      <mss:type>0</mss:type>
      <mss:values_array>
        <mss:value>true</mss:value>
      </mss:values_array>
    </mss:task>
    <mss:task>
      <mss:task_id>10</mss:task_id>
      <mss:short_desc>SEARCH: Special fasta databases that override the default setting</mss:short_desc>
      <mss:long_desc>If 'Allow all fasta databases to be searched' is set, then all databases except those listed here can be searched. If 'Allow all fasta databases to be searched' is not included, then only databases listed here can be searched. Enter a list of database names separated by commas - e.g. MSDB, NCBInr</mss:long_desc>
      <mss:task_name>SECTASK_NAMEDFASTA</mss:task_name>
      <mss:type>10</mss:type>
      <mss:values_array></mss:values_array>
    </mss:task>
    <mss:task>
      <mss:task_id>11</mss:task_id>
      <mss:short_desc>SEARCH: Maximum variable modifications for standard searches</mss:short_desc>
      <mss:long_desc>The maximum number of variable modifications allowed for a standard search. Must be a number between 1 and 32</mss:long_desc>
      <mss:task_name>SECTASK_MAXVARMODS</mss:task_name>
      <mss:type>2</mss:type>
      <mss:values_array></mss:values_array>
    </mss:task>
    <mss:task>
      <mss:task_id>12</mss:task_id>
      <mss:short_desc>SEARCH: Maximum variable modifications for error tolerant searches</mss:short_desc>
      <mss:long_desc>This applies to both the original style error tolerant search and the new combined style error tolerant search. The value may be different from the number allowed for a normal search. The limit must be between 0 and 31.</mss:long_desc>
      <mss:task_name>SECTASK_MAXETVARMODS</mss:task_name>
      <mss:type>2</mss:type>
      <mss:values_array></mss:values_array>
    </mss:task>

    <mss:task>
      <mss:task_id>13</mss:task_id>
      <mss:short_desc>VIEW: See search results from other people in your own group</mss:short_desc>
      <mss:long_desc>You can see your own search results without any special permissions. Adding this task allows a user to see searches submitted by other users who belong to the same group.</mss:long_desc>
      <mss:task_name>SECTASK_SEESEARCHINGROUP</mss:task_name>
      <mss:type>11</mss:type>
      <mss:values_array></mss:values_array>
    </mss:task>
    <mss:task>
      <mss:task_id>14</mss:task_id>
      <mss:short_desc>VIEW: See all search results with a USERID</mss:short_desc>
      <mss:long_desc>Adding this task allows a member of the group to see any search results that have a (non-zero) user ID. Searches without a USERID (prior to Mascot 2.1) or searches where security is disabled cannot be viewed.</mss:long_desc>
      <mss:task_name>SECTASK_SEEALLSEARCHESWITHUSERID</mss:task_name>
      <mss:type>0</mss:type>
      <mss:values_array>
        <mss:value>true</mss:value>
      </mss:values_array>
    </mss:task>
    <mss:task>
      <mss:task_id>15</mss:task_id>
      <mss:short_desc>VIEW: See search results without USERID field</mss:short_desc>
      <mss:long_desc>Adding this task allows a member of the group to see any search results that don't have a USERID (i.e. searches prior to Mascot 2.1) or searches with USERID=0 (Security Disabled).</mss:long_desc>
      <mss:task_name>SECTASK_SEEOLDSEARCHES</mss:task_name>
      <mss:type>0</mss:type>
      <mss:values_array>
        <mss:value>true</mss:value>
      </mss:values_array>
    </mss:task>
    <mss:task>
      <mss:task_id>16</mss:task_id>
      <mss:short_desc>VIEW: Allow user to view the search log</mss:short_desc>
      <mss:long_desc>Allow user to view the search log. They may not be able to view other searches depending on other VIEW: tasks.</mss:long_desc>
      <mss:task_name>SECTASK_USEMSREVIEWEXE</mss:task_name>
      <mss:type>0</mss:type>
      <mss:values_array>
        <mss:value>true</mss:value>
      </mss:values_array>
    </mss:task>

    <mss:task>
      <mss:task_id>17</mss:task_id>
      <mss:short_desc>GENERAL: View config files using ms-status</mss:short_desc>
      <mss:long_desc>This is a basic requirement for client applications. Adding this task allows client applications to read the configuration files such as the mod_file, enzymes file and mascot.dat.</mss:long_desc>
      <mss:task_name>SECTASK_VIEWCONFIGUSINGMSSTATUS</mss:task_name>
      <mss:type>0</mss:type>
      <mss:values_array>
        <mss:value>true</mss:value>
      </mss:values_array>
    </mss:task>
    <mss:task>
      <mss:task_id>18</mss:task_id>
      <mss:short_desc>GENERAL: Allow user to modify their own profile</mss:short_desc>
      <mss:long_desc>Allow user to modify their own profile. For example, allow them to change their email address.</mss:long_desc>
      <mss:task_name>SECTASK_MODIFYOWNPROFILE</mss:task_name>
      <mss:type>0</mss:type>
      <mss:values_array>
        <mss:value>true</mss:value>
      </mss:values_array>
    </mss:task>

    <mss:task>
      <mss:task_id>19</mss:task_id>
      <mss:short_desc>CLIENT: Mascot Daemon is allowed to submit searches</mss:short_desc>
      <mss:long_desc>Mascot Daemon is allowed to submit searches. Without this, Mascot Daemon cannot connect to the Mascot server.</mss:long_desc>
      <mss:task_name>SECTASK_DAEMONCLIENT</mss:task_name>
      <mss:type>0</mss:type>
      <mss:values_array>
        <mss:value>true</mss:value>
      </mss:values_array>
    </mss:task>
    <mss:task>
      <mss:task_id>20</mss:task_id>
